name: STM32CubeIDE Build

on:
  push:
    branches: [ "main"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  stm32cubeide_build:
    name: STM32CubeIDE Docker Build
    runs-on: ubuntu-latest

    container:
      image: xanderhendriks/stm32cubeide:16.0
      options: --privileged

    steps:

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git build-essential cmake gcc-arm-none-eabi binutils-arm-none-eabi

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Make build scripts executable
        run: |
          chmod +x ./zeropilot4.0/hwbuild.bash
          chmod +x ./zeropilot4.0/lint.bash

      - name: Build zeropilot4.0 library (CMake)
        working-directory: ./zeropilot4.0
        run: |
          bash ./hwbuild.bash -c -b l552 &
          bash ./hwbuild.bash -c -b l562 &
          wait

      - name: Build l552 board (STM32CubeIDE)
        run: |
          stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data /tmp/stm-workspace -import ./stm32l552xx
          headless-build.sh -data /tmp/stm-workspace -build stm32l552xx/Debug

      - name: Build l562 board (STM32CubeIDE)
        run: |
          stm32cubeide --launcher.suppressErrors -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -data /tmp/stm-workspace -import ./stm32l562xx
          headless-build.sh -data /tmp/stm-workspace -build stm32l562xx/Debug
